language: node_js
node_js:
- '5'
before_install:
- npm install -g codeclimate-test-reporter
script: npm test -- --browsers PhantomJS
after_script:
- npm run coverage-remap
- codeclimate-test-reporter < coverage/coverage-remapped.lcov
addons:
  code_climate:
    repo_token:
      secure: PEdCMJnYBzMaFLKGk9cz0C2tisqDP4idKnzOgfVhQxcTziUsvYWjuJF0UHHkpMrdhF/2YLe3ak4NsnzWzwllJdj/2JN33jkDcRJNKLwFSGf5Rq+kER/ch80Ycb6UHb9tNfeA4vYdM64LhHZhxZrajiqei+kHKImuGWYgon803TuAjnpVQYxXGf7n5MzU3o8j8CFtJXP5wmSg3u55ttgHo7HGq2T/ugUOAxVfy41RRw1VDL1fptCjVo9ZAkwv1KGK1ZQ0jRrmaL+OCKVu1lE49qXTcJ8kuec8sp/1WxE2DwUZVtFa4vX/1ErgpsD9YkmZ1G0Mx4qPEmObvR14vvdOcwXOm6z23+0t6pgy2o+xH1fHOyvYbR5/5VynXC0E+UdL4qpHk00lf86DSMchbl3aBq9OjG2ax0WAaA0dLg71bGDgfAWPJ0z1E+hvQom3JbwLaxvKK0M9/WaraaIRiWkaQSFsMJ4j5BdtGZfsEKwsaZi6cYD8ubR2h4/zYMB97thCT3Vp/7G0KBcLHQOks2n9UskRPwlWFYWAG8VvCRxL7T6yo/RsmndIKNrl3KnsUmLYe1xHehiRzsvjK1U3sUYKo3TbITuKzJx16rxvXVrOZNPQljUr9gB522uRBNzLFbl5Z5bXp/VAjrbuE+prqVM+JtEU+PR0iLH23J/7/5XMEzU=
deploy:
  provider: npm
  email: jasondcalkins@gmail.com
  api_key:
    secure: u/NqXdFu8QSsewGZmBY8PyeRevzrAslQPuH4B1w6Lk+i/zl3OAumhi+/MsfkmHbKV4R6ENKT0Uno7E7ZgwPyByjJM5G8npXLvaizB1p799BbRFwRF3q8XQPikbdZcKSvebYxXx1+h3GQdfVo2QIolom783k1JQVlnjh8EJP2q4iLiCRjAKmVxF0gl75WGOLSi3Jts94cfo9OrHxxflUyUugB26jBBGrnCjOlIpBhqYw1uKapMHIvG5P1o+VCdVCTt6Xow7FVa166xJ4IFbgQBEb79b8fIAz/ZxzMFBZAMsHQDaZwlwx5YaampMr7geYKB/9Qd/pbetcmD4OQC/RleOWlOtXLd6CzZugoP3UyJJ67SEBP2G8VmxT0JZYJtO8Us0gtmgIYm0+/m4JaXfreHWCaywFb/RKcq+qs7XsxOBfJviCAXZhnJqZgNfLaMvA0FCtYm9EXTCdMRCb6NTV7J4oUZuMh/YtQYej2rTV8gUJelCqn2wSXisD90/XkRq95wyWsr0dpcSyKJ6Pbfgk74IIfuY85/OuNfM4Dbhe2RgDvIxdMLDA+6Iq2eNAxj6h5inDlowhT29kibWmAItgAEACGC+R2QHvbyu//doXqNrZH2nfX+HeQbv09zpD1vqmo2/8u83x7akvDrqsDifQpotY1L2vlUuXnODlEYlG2Ek0=
  on:
    tags: true
    repo: jdcalkins/ng2-data-table
env:
  global:
    secure: EetZRe9XQKvc4USsK40aYOZ8kInjpSH2xj4H9zeFPTYFCjxoY4K+HtAnrX7h9aztxo4KEcdEGVLmwYkX9INEiRwRDmXg1meDG5Ecy4QzEoHVWQH8x8b6r+5AeasKcgQu1yzpb6vljUAlMsgWLD0cTf645IeCcI7rAmekvo6lNz2qvnB7fXIMuBk4fVdZkiqB5XpA/JxD8JwDluRVlpGzNjRi/pc/gFkY15xLh5VeZ1bnEd85tCx/qMoOMhXO1ZC7mSdyUqXi2L6k6FAZObfKdzMbdwBHm4c6cogEjyMtQqgEQ5PqBrQQAwqWgbUkrGYw/04mtVxh/BPAta6m8OfiHUzb7wvxJEKbPNlaeljHWgfb1B1u/7wI1BlSnvcS5xV5L+gMo/RsykLKnRfPjl1K57a9QRHTODsG+0K4HHCryuX2uyP8aJuRmVqTOpVqHXuS7zD5kuyb/jsZ6RFUjhanSlHEwhcxKBX8VA4sYsJpxb0vaJ+U2cEwBy/z1JR2ud/xdnM+Gh+gnPKfX2ljEBnliOoGfU3CMzBaPVBB13G9KHKRKJWzwY4AvYcqSwAo+dgAK41er9sXnbTK1cKeQEyR56JcGBo4J0ptFlLif59pGCOA/puGFWP+av1T8u/8EtZPw5l2GMyW1DsU2BiGzjoec4u4g8NDJcNZPG/9Nd6XXkA=
